### PR TITLE
added error log message for all tried paths #164

### PR DESCRIPTION
**Pull request by anuraag-khare**
### **What is this change?**

This PR adds additional logs to print error messages for all the tried supplementary search paths if lib  not found.

### Does this PR resolve or contribute to any issues?

This PR contributes towards issue #164 for adding error logs.

### CODE REVIEW

**Comment by kleag** [comment]
Thanks a lot for your PR. It implements most of what I was thinking for #164 but the messages should not include only the file name but also the error string obtained with `libhandle->errorString()`. This is because the library can in fact be found but fail to load due to a missing symbol for example. The message could be:
```
Failed to load <library> from <filename> due to <errorString>
```

**Comment by slyFox1999** [comment]
> Thanks a lot for your PR. It implements most of what I was thinking for #164 but the messages should not include only the file name but also the error string obtained with `libhandle->errorString()`. This is because the library can in fact be found but fail to load due to a missing symbol for example. The message could be:
> 
> ```
> Failed to load <library> from <filename> due to <errorString>
> ```

Thanks for correction. refactored the error string.

**Comment by kleag** [comment]
There is still a little problem: the `errorString` that you have added to the debug message comes from the last failure while it should come from the failure associated to the path. So you have to forge your message when you add data to `triedPaths` at line 192, or store pairs (path, error string) in `triedPaths` and forge the messages when using them.

**Review by kleag — APPROVED** [review]
Seems good to me now. Thanks again a lot for you contribution!

**Pull request merged**
